services:
  node-1:
    image: cassandra:5.0
    ports:
      - '7000:7000'
      - '7001:7001'
      - '7199:7199'
      - '9042:9042'
      - '9160:9160'
    volumes:
      - './nodes/node1:/var/lib/cassandra'
    networks:
      cassandra:
        ipv4_address: 168.16.238.1
    healthcheck:
      test: ["CMD-SHELL", "cqlsh", "exit;\n"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 30s
  node-2:
    image: cassandra:5.0
    ports:
      - '9043:9042'
    volumes:
      - './nodes/node2:/var/lib/cassandra'
    environment:
      - CASSANDRA_SEEDS=168.16.238.1
    networks:
      cassandra:
        ipv4_address: 168.16.238.2
    healthcheck:
      test: ["CMD-SHELL", "cqlsh", "exit;\n"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 30s
    depends_on:
      node-1:
        condition: service_healthy
  node-3:
    image: cassandra:5.0
    ports:
      - '9044:9042'
    volumes:
      - './nodes/node3:/var/lib/cassandra'
    environment:
      - CASSANDRA_SEEDS=168.16.238.1
    networks:
      cassandra:
        ipv4_address: 168.16.238.3
    healthcheck:
      test: ["CMD-SHELL", "cqlsh", "exit;\n"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 30s
    depends_on:
      node-2:
        condition: service_healthy

networks:
  cassandra:
    ipam:
      driver: default
      config:
        - subnet: "168.16.238.0/10"
